// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/saas-premium/Clients.tsx": () => import("../components/mockups/saas-premium/Clients.tsx"),
  "./components/mockups/saas-premium/Dashboard.tsx": () => import("../components/mockups/saas-premium/Dashboard.tsx"),
  "./components/mockups/saas-premium/Sessions.tsx": () => import("../components/mockups/saas-premium/Sessions.tsx")
};
